
name: main

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Get PR details
        id: pr
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            return pr.data;

      - name: Check all reviews
        id: check_reviews
        uses: actions/github-script@v6
        with:
          script: |
            const { data: reviews } = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const approvals = reviews.filter(review => review.state === 'APPROVED');
            const unique_approvers = [...new Set(approvals.map(approval => approval.user.id))];
            core.setOutput("all_approved", unique_approvers.length >= context.payload.pull_request.requested_reviewers.length);
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Merge Pull Request
        if: steps.check_reviews.outputs.all_approved == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
